application: genuine-amulet-864
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /myface\.jpg
  static_files: thriftshop/myface.jpg
  upload: thriftshop/myface\.jpg

- url: /(.*\.html)
  static_files: thriftshop/\1
  upload: thriftshop/(.*\.html)

- url: /js/(.*\.js)
  mime_type: text/javascript
  static_files: thriftshop/js/\1
  upload: thriftshop/js/(.*\.js)

- url: /css/(.*\.css)
  mime_type: text/css
  static_files: thriftshop/css/\1
  upload: thriftshop/css/(.*\.css)

- url: /img/(.*\.jpg)
  mime_type: image/jpeg
  static_files: thriftshop/img/\1
  upload: thriftshop/css/(.*\.jpg)

- url: /img/(.*\.png)
  mime_type: image/png
  static_files: thriftshop/img/\1
  upload: thriftshop/css/(.*\.png)
  
- url: .*
  script: main.app

- url: /(.*\.php)
  static_files: thriftshop/\1
  upload: thriftshop/(.*\.php) 

libraries:
- name: webapp2
  version: "2.5.2"
